eProject_Group1_sem3_batch151_152/LaundryStore/LaundryStore/Models/Worker.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.PayRollsWorkers = new HashSet<PayRollsWorker>();
            this.Works = new HashSet<Work>();
        }
    
        public int id { get; set; }
        public string workerName { get; set; }
        public Nullable<int> phone { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dayOfBirth { get; set; }
        public string avatar { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<long> contactSalary { get; set; }
        public string unitSalary { get; set; }
        public Nullable<int> workTime { get; set; }
        public string schedule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayRollsWorker> PayRollsWorkers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work> Works { get; set; }
    }
}

eProject_Group1_sem3_batch151_152/LaundryStore/LaundryStore/Areas/Admin/Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LaundryStore.Models;

namespace LaundryStore.Areas.Admin.Controllers
{
    public class WorkersController : Controller
    {
        private LAUNDRY_PROJECTEntities db = new LAUNDRY_PROJECTEntities();

        // GET: Admin/Workers
        public ActionResult Index()
        {
            List<Worker> list = null;
            list = db.Workers.Where(e => e.status == true).ToList();
            return View(list);
        }

        // GET: Admin/Workers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = db.Workers.Find(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }

        // GET: Admin/Workers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Workers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,workerName,phone,address,gender,dayOfBirth,avatar,status,dateStart,dateEnd,contactSalary,unitSalary,workTime,schedule")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                db.Workers.Add(worker);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(worker);
        }

        // GET: Admin/Workers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = db.Workers.Find(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }

        // POST: Admin/Workers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,workerName,phone,address,gender,dayOfBirth,avatar,status,dateStart,dateEnd,contactSalary,unitSalary,workTime,schedule")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(worker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(worker);
        }

        // GET: Admin/Workers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = db.Workers.Find(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }

        // POST: Admin/Workers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Worker worker = db.Workers.Find(id);
            db.Workers.Remove(worker);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eProject_Group1_sem3_batch151_152/LaundryStore/LaundryStore/Areas/Admin/Views/Workers/Create.cshtml
@model LaundryStore.Models.Worker

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm("Create", "Workers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <!-- Main Content Start -->
        <section class="main--content">
            <div class="panel">
                <!-- Records Header Start -->
                <div class="records--header">
                    <div class="title fa-shopping-bag">
                        <h3 class="h3">Worker Management</h3>
                    </div>
                    <div class="actions">
                        <a style="margin-right:10px" class="addProduct btn btn-lg btn-rounded btn-info" title="Back" href="@Url.Action("Index", "Workers")">
                            <span>BACK</span>
                        </a>
                        <div style="margin-right:10px" class="addProduct btn btn-sm btn-rounded btn-warning">
                            <div>
                                <button type="submit" class="btn btn-warning"><b>CREATE WORKER</b></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Records Header End -->
            </div>

            <div class="panel">

                <!-- Edit Product Start -->
                <div class="records--body">
                    <div class="title">
                        <h6 class="h6">CREATE WORKER</h6>
                    </div>

                    <!-- Tabs Nav Start -->
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a href="#tab01" data-toggle="tab" class="nav-link active">Create</a>
                        </li>
                    </ul>
                    <!-- Tabs Nav End -->
                    <!-- Tab Content Start -->
                    <div class="tab-content">
                        <!-- Tab Pane Start -->
                        <div class="tab-pane fade show active" id="tab01">
                            <div class="row">
                                <div class="form-group col-sm-6">
                                    <b><span>Worker Name</span></b>
                                    @Html.EditorFor(model => model.workerName, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                    @Html.ValidationMessageFor(model => model.workerName, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Phone</span></b>
                                    @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                    @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Address</span></b>
                                    @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Gender</span></b>
                                    @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                    @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Day of birth</span></b>
                                    @Html.EditorFor(model => model.dayOfBirth, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                    @Html.ValidationMessageFor(model => model.dayOfBirth, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Date start</span></b>
                                    @Html.EditorFor(model => model.dateStart, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                    @Html.ValidationMessageFor(model => model.dateStart, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Contact salary</span></b>
                                    @Html.EditorFor(model => model.contactSalary, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                    @Html.ValidationMessageFor(model => model.contactSalary, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Unit salary</span></b>
                                    @Html.EditorFor(model => model.unitSalary, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                    @Html.ValidationMessageFor(model => model.unitSalary, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Work time</span></b>
                                    @Html.EditorFor(model => model.workTime, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                    @Html.ValidationMessageFor(model => model.workTime, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Schedule</span></b>
                                    @Html.EditorFor(model => model.schedule, new { htmlAttributes = new { @class = "form-control", @required = true } })
                                    @Html.ValidationMessageFor(model => model.schedule, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <div class="checkbox">
                                        <b><span>Status</span></b>
                                        @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Avatar</span></b>
                                    <input class="form-control" type="file" name="avatar" />
                                </div>
                            </div>

                        </div>
                        <!-- Tab Pane End -->
                    </div>
                    <!-- Tab Content End -->
                </div>
                <!-- Edit Product End -->
            </div>
        </section>
    </div>
}

eProject_Group1_sem3_batch151_152/LaundryStore/LaundryStore/Areas/Admin/Views/Workers/Delete.cshtml
@model LaundryStore.Models.Worker

@{
    Layout = null;
}

<!DOCTYPE html>

<!-- Modal -->
<div id="deleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <i class="fas fa-exclamation-triangle" style="font-size:40px; margin:0 44%; color:orange" ;></i>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body" style="text-align:center">
                <h3><b>Are you sure delete worker ?</b></h3>
                <h4>You will not be able to recover this worker !</h4>
            </div>
            <div class="modal-footer editModalFooter">
                @using (Html.BeginForm("Delete", "Workers", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-info cancel" data-dismiss="modal"><b>Cancel</b></button>
                    <button type="submit" class="btn btn-warning yes"><b>Yes, delete it !</b></button>
                }
            </div><!-- /.modal-footer -->
        </div>
    </div>
</div>
<style>
    .editModalFooter {
        justify-content: center;
    }

    .cancel {
        width: 205px;
        margin-right: 10px
    }

    .yes {
        width: 205px;
        margin-top: 0px
    }
</style>

eProject_Group1_sem3_batch151_152/LaundryStore/LaundryStore/Areas/Admin/Views/Workers/Details.cshtml
@model LaundryStore.Models.Worker

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Main Content Start -->
<section class="main--content">
    <div class="panel container-fluid">
        <!-- Records Header Start -->
        <div class="records--header">
            <div class="title fa-shopping-bag">
                <h3 class="Workers Management</h3>
            </div>
            <div class="actions">
                <a style="margin-right:10px" class="addProduct btn btn-lg btn-rounded btn-info" title="Back" href="@Url.Action("Index", "Workers")">
                    <span>BACK</span>
                </a>
                <a class="addProduct btn btn-lg btn-rounded btn-warning" title="Edit" href="@Url.Action("Edit", "Workers", new { id = Model.id })">
                    <span>EDIT WORKERS</span>
                </a>
            </div>
        </div>
        <!-- Records Header End -->
    </div>

    <div class="panel">

        <!-- View Order Start -->
        <div class="records--body">
            <div class="title">
                <h6 class="h6"><span class="text-lightergray">Detail Worker</span></h6>
            </div>

            <!-- Tabs Nav Start -->
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="#tab01" data-toggle="tab" class="nav-link active">Detail</a>
                </li>
            </ul>
            <!-- Tabs Nav End -->
            <!-- Tab Content Start -->
            <div class="tab-content">
                <!-- Tab Pane Start -->
                <div class="tab-pane fade show active" id="tab01">
                    <h4 class="subtitle">Other Information</h4>
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-simple">
                                <tbody>
                                    <tr>
                                        <td>ID</td>
                                        <th>@Html.DisplayFor(model => model.id)</th>
                                    </tr>
                                    <tr>
                                        <td>Worker Name</td>
                                        <th>@Html.DisplayFor(model => model.workerName)</th>
                                    </tr>
                                    <tr>
                                        <td>Phone</td>
                                        <th>@Html.DisplayFor(model => model.phone)</th>
                                    </tr>
                                    <tr>
                                        <td>Address</td>
                                        <th>@Html.DisplayFor(model => model.address)</th>
                                    </tr>
                                    <tr>
                                        <td>Gender</td>
                                        <th>@Html.DisplayFor(model => model.gender)</th>
                                    </tr>
                                    <tr>
                                        <td>Day of birth</td>
                                        <th>@Html.DisplayFor(model => model.dayOfBirth)</th>
                                    </tr>
                                    <tr>
                                        <td>Avatar</td>
                                        <th>@Html.DisplayFor(model => model.avatar)</th>
                                    </tr>

                                </tbody>
                            </table>
                        </div>

                        <div class="col-md-6">
                            <table class="table table-simple">
                                <tbody>
                                    <tr>
                                        <td>Status</td>
                                        <th>
                                            @if (Model.status == true)
                                            {
                                                <span class="label label-success">Yes</span>
                                            }
                                            else
                                            {
                                                <span class="label label-danger">No</span>
                                            }
                                        </th>
                                    </tr>
                                    <tr>
                                        <td>Date start</td>
                                        <th>@Html.DisplayFor(model => model.dateStart)</th>
                                    </tr>
                                    <tr>
                                        <td>Date end</td>
                                        <th>@Html.DisplayFor(model => model.dateEnd)</th>
                                    </tr>
                                    <tr>
                                        <td>Contact salary</td>
                                        <th>@Html.DisplayFor(model => model.contactSalary)</th>
                                    </tr>
                                    <tr>
                                        <td>Unit salary</td>
                                        <th>@Html.DisplayFor(model => model.unitSalary)</th>
                                    </tr>
                                    <tr>
                                        <td>Work time</td>
                                        <th>@Html.DisplayFor(model => model.workTime)</th>
                                    </tr>
                                    <tr>
                                        <td>Schedule</td>
                                        <th>@Html.DisplayFor(model => model.schedule)</th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- Tab Pane End -->
            </div>
            <!-- Tab Content End -->
        </div>
        <!-- View Order End -->
    </div>
</section>
<!-- Main Content End -->

eProject_Group1_sem3_batch151_152/LaundryStore/LaundryStore/Areas/Admin/Views/Workers/Edit.cshtml
@model LaundryStore.Models.Worker

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.dateStart)


        <!-- Main Content Start -->
        <section class="main--content">
            <div class="panel">
                <!-- Records Header Start -->
                <div class="records--header">
                    <div class="title fa-shopping-bag">
                        <h3 class="h3">Worker Management</h3>
                    </div>
                    <div class="actions">
                        <a style="margin-right:10px" class="addProduct btn btn-lg btn-rounded btn-info" title="Back" href="@Url.Action("Index", "Workers")">
                            <span>BACK</span>
                        </a>
                        <div style="margin-right:10px" class="addProduct btn btn-sm btn-rounded btn-warning">
                            <div>
                                <button type="submit" class="btn btn-warning"><b>EDIT WORKER</b></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Records Header End -->
            </div>

            <div class="panel">

                <!-- Edit Product Start -->
                <div class="records--body">
                    <div class="title">
                        <h6 class="h6">EDIT WORKER</h6>
                    </div>

                    <!-- Tabs Nav Start -->
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a href="#tab01" data-toggle="tab" class="nav-link active">Edit</a>
                        </li>
                    </ul>
                    <!-- Tabs Nav End -->
                    <!-- Tab Content Start -->
                    <div class="tab-content">
                        <!-- Tab Pane Start -->
                        <div class="tab-pane fade show active" id="tab01">
                            <div class="row">
                                <div class="form-group col-sm-6">
                                    <b><span>Worker Name</span></b>
                                    @Html.EditorFor(model => model.workerName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.workerName, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Phone</span></b>
                                    @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Address</span></b>
                                    @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Gender</span></b>
                                    @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Date of birth</span></b>
                                    @Html.EditorFor(model => model.dayOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.dayOfBirth, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <div class="checkbox">
                                        <b><span>Status</span></b>
                                        @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Date end</span></b>
                                    @Html.EditorFor(model => model.dateEnd, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.dateEnd, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Contact salary</span></b>
                                    @Html.EditorFor(model => model.contactSalary, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.contactSalary, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Unit salary</span></b>
                                    @Html.EditorFor(model => model.unitSalary, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.unitSalary, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Work time</span></b>
                                    @Html.EditorFor(model => model.workTime, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.workTime, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Schedule</span></b>
                                    @Html.EditorFor(model => model.schedule, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.schedule, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-sm-6">
                                    <b><span>Avatar</span></b>
                                    <input class="form-control" type="file" name="avatar" />
                                </div>
                            </div>
                        </div>
                        <!-- Tab Pane End -->
                    </div>
                    <!-- Tab Content End -->
                </div>
                <!-- Edit Product End -->
            </div>
        </section>
    </div>
    <!-- Main Content End -->
}